#!/usr/bin/env bash
set -euo pipefail

# Verification script for 2-level HIBS implementation using provided test vectors.
# Runs pkg -> signer1 -> signer2 -> verifier for n = 1,2,3 and
# compares generated outputs against Correct_*.txt reference files.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# Files generated by the programs (relative to SCRIPT_DIR)
GENERATED_FILES=(
  "mpk.txt"
  "sk_ID1.txt"
  "Q_ID1.txt"
  "Q_ID2.txt"
  "sig_s.txt"
  "sig_h.txt"
  "verification.txt"
)

clean_generated_files() {
  for f in "${GENERATED_FILES[@]}"; do
    rm -f "$f"
  done
}

# Compare two files and abort on mismatch, similar to VerifyAraziQi.sh
# Args: generated expected label
cmp_or_fail() {
  local generated="$1"
  local expected="$2"
  local msg="$3"

  if ! [[ -f "$generated" ]]; then
    echo "ERROR: Generated file '$generated' not found ($msg)." >&2
    exit 1
  fi
  if ! [[ -f "$expected" ]]; then
    echo "ERROR: Expected file '$expected' not found ($msg)." >&2
    exit 1
  fi

  # Normalize contents (strip whitespace/newlines) before comparison
  local gen_norm exp_norm
  gen_norm="$(tr -d ' \t\r\n' < "$generated")"
  exp_norm="$(tr -d ' \t\r\n' < "$expected")"

  if [[ "$gen_norm" != "$exp_norm" ]]; then
    echo "ERROR: Mismatch for $msg (after normalizing whitespace)." >&2
    echo "  Generated ($generated): $gen_norm" >&2
    echo "  Expected  ($expected): $exp_norm" >&2
    exit 1
  fi

  echo "  OK: $msg"
}

# Ensure binaries are compiled in this directory.
compile_binaries() {
  echo "[INFO] Compiling HIBS binaries in $SCRIPT_DIR ..."
  gcc -Wall -Wextra -O2 pkg.c RequiredFunctions.c -o pkg -lcrypto
  gcc -Wall -Wextra -O2 signer1.c RequiredFunctions.c -o signer1 -lcrypto
  gcc -Wall -Wextra -O2 signer2.c RequiredFunctions.c -o signer2 -lcrypto
  gcc -Wall -Wextra -O2 verifier.c RequiredFunctions.c -o verifier -lcrypto
  echo "[INFO] Compilation done."
}

compile_binaries

for n in 1 2 3; do
  echo "========================================"
  echo "[Test $n] Starting HIBS verification"

  clean_generated_files

  # Reference files for this n
  correct_msk="Correct_msk_${n}.txt"
  correct_mpk="Correct_mpk_${n}.txt"
  correct_b1="Correct_signer1_b1_${n}.txt"
  correct_sk_ID1="Correct_sk_ID1_${n}.txt"
  correct_Q_ID1="Correct_Q_ID1_${n}.txt"
  correct_b2="Correct_signer2_b2_${n}.txt"
  correct_r="Correct_signer2_r_${n}.txt"
  correct_msg="Correct_message_${n}.txt"
  correct_Q_ID2="Correct_Q_ID2_${n}.txt"
  correct_sig_s="Correct_sig_s_${n}.txt"
  correct_sig_h="Correct_sig_h_${n}.txt"

  echo "[Test $n] Running pkg..."
  ./pkg "./$correct_msk"

  echo "[Test $n] Verifying pkg outputs..."
  cmp_or_fail "mpk.txt" "$correct_mpk" "mpk (n=${n})"

  echo "[Test $n] Running signer1..."
  ./signer1 ./Correct_ID1.txt "./$correct_b1" "./$correct_msk"

  echo "[Test $n] Verifying signer1 outputs..."
  cmp_or_fail "sk_ID1.txt" "$correct_sk_ID1" "sk_ID1 (n=${n})"
  cmp_or_fail "Q_ID1.txt" "$correct_Q_ID1" "Q_ID1 (n=${n})"

  echo "[Test $n] Running signer2..."
  ./signer2 sk_ID1.txt "./$correct_b2" "./$correct_r" ./Q_ID1.txt ./Correct_ID2.txt "./$correct_msg"

  echo "[Test $n] Verifying signer2 outputs..."
  cmp_or_fail "Q_ID2.txt" "$correct_Q_ID2" "Q_ID2 (n=${n})"
  cmp_or_fail "sig_s.txt" "$correct_sig_s" "sig_s (n=${n})"
  cmp_or_fail "sig_h.txt" "$correct_sig_h" "sig_h (n=${n})"

  echo "[Test $n] Running verifier..."
  ./verifier ./Correct_ID1.txt ./Correct_ID2.txt "./$correct_msg" ./mpk.txt ./Q_ID1.txt ./Q_ID2.txt ./sig_s.txt ./sig_h.txt

  echo "[Test $n] Verifying verifier output..."
  # Per your specification, verification.txt is compared to Correct_sig_h_n.txt
  cmp_or_fail "verification.txt" "$correct_sig_h" "verification (n=${n}) vs Correct_sig_h_${n}.txt"

  echo "[Test $n] SUCCESS: All comparisons passed."
  echo
done

echo "========================================"
echo "ALL TESTS PASSED: HIBS implementation matches all provided test vectors."

# Cleanup: remove all non-Correct .txt files generated during testing
echo "Cleaning up generated .txt files (keeping only 'Correct*')..."
find . -maxdepth 1 -type f -name '*.txt' ! -name 'Correct*' -exec rm -f {} +
